name: Tests

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *' # monthly

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # The first supported version on conda-forge and the latest available
        python-version: ['3.6', '3.12']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest
